// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PeaceNest.Api.Common.Database;
using PeaceNest.Api.Common.Database.Entities;

#nullable disable

namespace PeaceNest.Api.Common.Database.Migrations
{
    [DbContext(typeof(PeaceNestDbContext))]
    [Migration("20260624015412_AddFamilyDepartureAndRecovery")]
    partial class AddFamilyDepartureAndRecovery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "activity_type", new[] { "comment_added", "family_created", "family_plan_created", "monthly_recap_generated", "plan_completed", "plan_updated", "vote_cast" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "family_invitation_status", new[] { "accepted", "expired", "pending", "revoked" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "family_join_code_status", new[] { "active", "capacity_reached", "expired", "revoked" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "family_join_request_status", new[] { "approved", "cancelled", "expired", "pending", "rejected", "withdrawn" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "family_member_role", new[] { "adult_member", "child_member", "owner", "parent_admin", "viewer" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "family_member_status", new[] { "active", "removed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "family_recovery_code_status", new[] { "active", "used" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_type", new[] { "comment_added", "family_join_request_approved", "family_join_request_created", "family_join_request_rejected", "family_plan_created", "milestone_completed", "monthly_recap_ready", "plan_updated", "vote_cast" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "plan_status", new[] { "active", "archived", "completed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "plan_type", new[] { "milestone", "want_need" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "recap_period_type", new[] { "monthly" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "score_level", new[] { "high", "low", "medium" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vote_value", new[] { "neutral", "not_now", "support" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "want_need_kind", new[] { "need", "want" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<ActivityType>("ActivityType")
                        .HasColumnType("activity_type")
                        .HasColumnName("activity_type");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid?>("RecapId")
                        .HasColumnType("uuid")
                        .HasColumnName("recap_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_activity_logs_actor_user_id");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_activity_logs_comment_id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_activity_logs_plan_id");

                    b.HasIndex("RecapId")
                        .HasDatabaseName("ix_activity_logs_recap_id");

                    b.HasIndex("FamilyId", "CreatedAt")
                        .HasDatabaseName("ix_activity_logs_family_id_created_at");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_comments_author_user_id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_comments_parent_comment_id");

                    b.HasIndex("PlanId", "CreatedAt")
                        .HasDatabaseName("ix_comments_active_plan_id_created_at")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("preferred_currency");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_families_created_by_user_id");

                    b.ToTable("families", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.FamilyInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("InvitationCodeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("invitation_code_hash");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext")
                        .HasColumnName("invited_email");

                    b.Property<FamilyMemberRole>("InvitedRole")
                        .HasColumnType("family_member_role")
                        .HasColumnName("invited_role");

                    b.Property<FamilyInvitationStatus>("Status")
                        .HasColumnType("family_invitation_status")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserId")
                        .HasDatabaseName("ix_family_invitations_accepted_by_user_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_family_invitations_created_by_user_id");

                    b.HasIndex("InvitationCodeHash")
                        .IsUnique()
                        .HasDatabaseName("ux_family_invitations_invitation_code_hash")
                        .HasFilter("invitation_code_hash IS NOT NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_family_invitations_token_hash");

                    b.HasIndex("FamilyId", "InvitedEmail")
                        .HasDatabaseName("ix_family_invitations_pending_email")
                        .HasFilter("status = 'pending'::family_invitation_status");

                    b.ToTable("family_invitations", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.FamilyJoinCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<int>("MaxRequests")
                        .HasColumnType("integer")
                        .HasColumnName("max_requests");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer")
                        .HasColumnName("request_count");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<FamilyJoinCodeStatus>("Status")
                        .HasColumnType("family_join_code_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ux_family_join_codes_code_hash");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_family_join_codes_created_by_user_id");

                    b.HasIndex("FamilyId")
                        .IsUnique()
                        .HasDatabaseName("ux_family_join_codes_active_family")
                        .HasFilter("status = 'active'");

                    b.HasIndex("RevokedByUserId")
                        .HasDatabaseName("ix_family_join_codes_revoked_by_user_id");

                    b.ToTable("family_join_codes", null, t =>
                        {
                            t.HasCheckConstraint("ck_family_join_codes_max_requests", "max_requests > 0");

                            t.HasCheckConstraint("ck_family_join_codes_request_count", "request_count >= 0 AND request_count <= max_requests");
                        });
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.FamilyJoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<FamilyMemberRole?>("ApprovedRole")
                        .HasColumnType("family_member_role")
                        .HasColumnName("approved_role");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("JoinCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("join_code_id");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_user_id");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<FamilyJoinRequestStatus>("Status")
                        .HasColumnType("family_join_request_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("JoinCodeId")
                        .HasDatabaseName("ix_family_join_requests_join_code_id");

                    b.HasIndex("ReviewedByUserId")
                        .HasDatabaseName("ix_family_join_requests_reviewed_by_user_id");

                    b.HasIndex("FamilyId", "RequesterUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_family_join_requests_pending_family_requester")
                        .HasFilter("status = 'pending'");

                    b.HasIndex("FamilyId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_family_join_requests_family_status_created");

                    b.HasIndex("RequesterUserId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_family_join_requests_requester_status_created");

                    b.ToTable("family_join_requests", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Nickname")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nickname");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<FamilyMemberRole>("Role")
                        .HasColumnType("family_member_role")
                        .HasColumnName("role");

                    b.Property<FamilyMemberStatus>("Status")
                        .HasColumnType("family_member_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_family_members_user_id");

                    b.HasIndex("FamilyId", "Status")
                        .HasDatabaseName("ix_family_members_family_id_status");

                    b.HasIndex("FamilyId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_family_members_family_id_user_id");

                    b.ToTable("family_members", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.FamilyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<PlanType>("PlanType")
                        .HasColumnType("plan_type")
                        .HasColumnName("plan_type");

                    b.Property<int?>("PriorityRank")
                        .HasColumnType("integer")
                        .HasColumnName("priority_rank");

                    b.Property<decimal>("PriorityScore")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("priority_score");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<PlanStatus>("Status")
                        .HasColumnType("plan_status")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_family_plans_category_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_family_plans_created_by_user_id");

                    b.HasIndex("FamilyId", "PriorityRank")
                        .HasDatabaseName("ix_family_plans_active_priority_rank")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("FamilyId", "PlanType", "Status")
                        .HasDatabaseName("ix_family_plans_family_id_plan_type_status");

                    b.ToTable("family_plans", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.FamilyRecoveryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("PurgeClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purge_claimed_at");

                    b.Property<FamilyRecoveryCodeStatus>("Status")
                        .HasColumnType("family_recovery_code_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ux_family_recovery_codes_code_hash");

                    b.HasIndex("CreatorUserId")
                        .HasDatabaseName("ix_family_recovery_codes_creator_user_id");

                    b.HasIndex("FamilyId")
                        .IsUnique()
                        .HasDatabaseName("ux_family_recovery_codes_active_family_id")
                        .HasFilter("status = 'active'");

                    b.HasIndex("Status", "ExpiresAt", "PurgeClaimedAt")
                        .HasDatabaseName("ix_family_recovery_codes_active_expiry_claim")
                        .HasFilter("status = 'active'");

                    b.ToTable("family_recovery_codes", null, t =>
                        {
                            t.HasCheckConstraint("ck_family_recovery_codes_expiry", "expires_at > created_at");
                        });
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.GoalStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompletedByUserId")
                        .HasDatabaseName("ix_goal_steps_completed_by_user_id");

                    b.HasIndex("PlanId", "SortOrder")
                        .HasDatabaseName("ix_goal_steps_active_plan_id_sort_order")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("goal_steps", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Memory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("caption");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("media_type");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("storage_path");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("storage_provider");

                    b.Property<DateTimeOffset?>("TakenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("thumbnail_path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_memories_plan_id");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_memories_uploaded_by_user_id");

                    b.HasIndex("FamilyId", "CreatedAt")
                        .HasDatabaseName("ix_memories_active_family_id_created_at")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("memories", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.MilestoneDetails", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("CelebrationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("celebration_notes");

                    b.Property<bool>("IncludeInRecap")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_recap");

                    b.Property<string>("MilestoneType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("milestone_type");

                    b.Property<string>("ReflectionPrompt")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reflection_prompt");

                    b.HasKey("PlanId");

                    b.ToTable("milestone_details", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Body")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<Guid?>("RelatedCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_comment_id");

                    b.Property<Guid?>("RelatedJoinRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_join_request_id");

                    b.Property<Guid?>("RelatedPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_plan_id");

                    b.Property<Guid?>("RelatedRecapId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_recap_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<NotificationType>("Type")
                        .HasColumnType("notification_type")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_notifications_actor_user_id");

                    b.HasIndex("RelatedCommentId")
                        .HasDatabaseName("ix_notifications_related_comment_id");

                    b.HasIndex("RelatedJoinRequestId")
                        .HasDatabaseName("ix_notifications_related_join_request_id");

                    b.HasIndex("RelatedPlanId")
                        .HasDatabaseName("ix_notifications_related_plan_id");

                    b.HasIndex("RelatedRecapId")
                        .HasDatabaseName("ix_notifications_related_recap_id");

                    b.HasIndex("FamilyId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_active_family_created")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("RecipientUserId", "ReadAt", "CreatedAt")
                        .HasDatabaseName("ix_notifications_active_recipient_read_created")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.PlanCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Icon")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId", "Name")
                        .HasDatabaseName("ix_plan_categories_active_name")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("FamilyId", "SortOrder")
                        .HasDatabaseName("ix_plan_categories_family_id_sort_order");

                    b.ToTable("plan_categories", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.PlanParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("Role")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_plan_participants_user_id");

                    b.HasIndex("PlanId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_plan_participants_plan_id_user_id");

                    b.ToTable("plan_participants", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.PlanVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<int>("PriorityPoints")
                        .HasColumnType("integer")
                        .HasColumnName("priority_points");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<VoteValue>("VoteValue")
                        .HasColumnType("vote_value")
                        .HasColumnName("vote_value");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_plan_votes_user_id");

                    b.HasIndex("PlanId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_plan_votes_plan_id_user_id");

                    b.ToTable("plan_votes", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reaction_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reactions_user_id");

                    b.HasIndex("CommentId", "UserId", "ReactionType")
                        .IsUnique()
                        .HasDatabaseName("ux_reactions_comment_user_type")
                        .HasFilter("comment_id IS NOT NULL");

                    b.HasIndex("PlanId", "UserId", "ReactionType")
                        .IsUnique()
                        .HasDatabaseName("ux_reactions_plan_user_type")
                        .HasFilter("plan_id IS NOT NULL");

                    b.ToTable("reactions", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Recap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("GeneratedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_by_user_id");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<RecapPeriodType>("PeriodType")
                        .HasColumnType("recap_period_type")
                        .HasColumnName("period_type");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Stats")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stats");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedByUserId")
                        .HasDatabaseName("ix_recaps_generated_by_user_id");

                    b.HasIndex("FamilyId", "PeriodType", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("ux_recaps_active_family_period")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("recaps", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.RecapItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("item_type");

                    b.Property<Guid?>("MemoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("memory_id");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("RecapId")
                        .HasColumnType("uuid")
                        .HasColumnName("recap_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("MemoryId")
                        .HasDatabaseName("ix_recap_items_memory_id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_recap_items_plan_id");

                    b.HasIndex("RecapId", "SortOrder")
                        .HasDatabaseName("ix_recap_items_recap_id_sort_order");

                    b.ToTable("recap_items", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("OnboardingCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboarding_completed_at");

                    b.Property<Guid>("SupabaseUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("supabase_user_id");

                    b.Property<string>("Timezone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_active_email")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("SupabaseUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_supabase_user_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.WantNeedDetails", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateOnly?>("DesiredByDate")
                        .HasColumnType("date")
                        .HasColumnName("desired_by_date");

                    b.Property<ScoreLevel>("EmotionalValueLevel")
                        .HasColumnType("score_level")
                        .HasColumnName("emotional_value_level");

                    b.Property<decimal?>("EstimatedCostAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimated_cost_amount");

                    b.Property<string>("EstimatedCostCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("estimated_cost_currency");

                    b.Property<string>("FundingNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("funding_notes");

                    b.Property<ScoreLevel>("ImportanceLevel")
                        .HasColumnType("score_level")
                        .HasColumnName("importance_level");

                    b.Property<WantNeedKind>("Kind")
                        .HasColumnType("want_need_kind")
                        .HasColumnName("kind");

                    b.Property<ScoreLevel>("UrgencyLevel")
                        .HasColumnType("score_level")
                        .HasColumnName("urgency_level");

                    b.HasKey("PlanId");

                    b.ToTable("want_need_details", (string)null);
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.ActivityLog", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "ActorUser")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Comment", "Comment")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Family", "Family")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.FamilyPlan", "Plan")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Recap", "Recap")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("RecapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");

                    b.Navigation("Comment");

                    b.Navigation("Family");

                    b.Navigation("Plan");

                    b.Navigation("Recap");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Comment", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "AuthorUser")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.FamilyPlan", "Plan")
                        .WithMany("Comments")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("ParentComment");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Family", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "CreatedByUser")
                        .WithMany("CreatedFamilies")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.FamilyInvitation", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "AcceptedByUser")
                        .WithMany("AcceptedInvitations")
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "CreatedByUser")
                        .WithMany("CreatedInvitations")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Family", "Family")
                        .WithMany("Invitations")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcceptedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.FamilyJoinCode", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "CreatedByUser")
                        .WithMany("CreatedJoinCodes")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Family", "Family")
                        .WithMany("JoinCodes")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "RevokedByUser")
                        .WithMany("RevokedJoinCodes")
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Family");

                    b.Navigation("RevokedByUser");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.FamilyJoinRequest", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Family", "Family")
                        .WithMany("JoinRequests")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.FamilyJoinCode", "JoinCode")
                        .WithMany("Requests")
                        .HasForeignKey("JoinCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "RequesterUser")
                        .WithMany("FamilyJoinRequests")
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "ReviewedByUser")
                        .WithMany("ReviewedFamilyJoinRequests")
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Family");

                    b.Navigation("JoinCode");

                    b.Navigation("RequesterUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.FamilyMember", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "User")
                        .WithMany("FamilyMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.FamilyPlan", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.PlanCategory", "Category")
                        .WithMany("Plans")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "CreatedByUser")
                        .WithMany("CreatedPlans")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Family", "Family")
                        .WithMany("Plans")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.FamilyRecoveryCode", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "CreatorUser")
                        .WithMany("FamilyRecoveryCodes")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Family", "Family")
                        .WithMany("RecoveryCodes")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.GoalStep", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "CompletedByUser")
                        .WithMany("CompletedGoalSteps")
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.FamilyPlan", "Plan")
                        .WithMany("GoalSteps")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompletedByUser");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Memory", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Family", "Family")
                        .WithMany("Memories")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.FamilyPlan", "Plan")
                        .WithMany("Memories")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "UploadedByUser")
                        .WithMany("UploadedMemories")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Plan");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.MilestoneDetails", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.FamilyPlan", "Plan")
                        .WithOne("MilestoneDetails")
                        .HasForeignKey("PeaceNest.Api.Common.Database.Entities.MilestoneDetails", "PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Notification", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "ActorUser")
                        .WithMany("TriggeredNotifications")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Family", "Family")
                        .WithMany("Notifications")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "RecipientUser")
                        .WithMany("ReceivedNotifications")
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Comment", "RelatedComment")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.FamilyJoinRequest", "RelatedJoinRequest")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedJoinRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.FamilyPlan", "RelatedPlan")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Recap", "RelatedRecap")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedRecapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");

                    b.Navigation("Family");

                    b.Navigation("RecipientUser");

                    b.Navigation("RelatedComment");

                    b.Navigation("RelatedJoinRequest");

                    b.Navigation("RelatedPlan");

                    b.Navigation("RelatedRecap");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.PlanCategory", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Family", "Family")
                        .WithMany("PlanCategories")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.PlanParticipant", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.FamilyPlan", "Plan")
                        .WithMany("Participants")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "User")
                        .WithMany("PlanParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.PlanVote", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.FamilyPlan", "Plan")
                        .WithMany("Votes")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "User")
                        .WithMany("PlanVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Reaction", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.FamilyPlan", "Plan")
                        .WithMany("Reactions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Recap", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Family", "Family")
                        .WithMany("Recaps")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.User", "GeneratedByUser")
                        .WithMany("GeneratedRecaps")
                        .HasForeignKey("GeneratedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("GeneratedByUser");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.RecapItem", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Memory", "Memory")
                        .WithMany("RecapItems")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.FamilyPlan", "Plan")
                        .WithMany("RecapItems")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeaceNest.Api.Common.Database.Entities.Recap", "Recap")
                        .WithMany("Items")
                        .HasForeignKey("RecapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Memory");

                    b.Navigation("Plan");

                    b.Navigation("Recap");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.WantNeedDetails", b =>
                {
                    b.HasOne("PeaceNest.Api.Common.Database.Entities.FamilyPlan", "Plan")
                        .WithOne("WantNeedDetails")
                        .HasForeignKey("PeaceNest.Api.Common.Database.Entities.WantNeedDetails", "PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Comment", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Notifications");

                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Family", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Invitations");

                    b.Navigation("JoinCodes");

                    b.Navigation("JoinRequests");

                    b.Navigation("Members");

                    b.Navigation("Memories");

                    b.Navigation("Notifications");

                    b.Navigation("PlanCategories");

                    b.Navigation("Plans");

                    b.Navigation("Recaps");

                    b.Navigation("RecoveryCodes");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.FamilyJoinCode", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.FamilyJoinRequest", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.FamilyPlan", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Comments");

                    b.Navigation("GoalSteps");

                    b.Navigation("Memories");

                    b.Navigation("MilestoneDetails");

                    b.Navigation("Notifications");

                    b.Navigation("Participants");

                    b.Navigation("Reactions");

                    b.Navigation("RecapItems");

                    b.Navigation("Votes");

                    b.Navigation("WantNeedDetails");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Memory", b =>
                {
                    b.Navigation("RecapItems");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.PlanCategory", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.Recap", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Items");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("PeaceNest.Api.Common.Database.Entities.User", b =>
                {
                    b.Navigation("AcceptedInvitations");

                    b.Navigation("ActivityLogs");

                    b.Navigation("Comments");

                    b.Navigation("CompletedGoalSteps");

                    b.Navigation("CreatedFamilies");

                    b.Navigation("CreatedInvitations");

                    b.Navigation("CreatedJoinCodes");

                    b.Navigation("CreatedPlans");

                    b.Navigation("FamilyJoinRequests");

                    b.Navigation("FamilyMemberships");

                    b.Navigation("FamilyRecoveryCodes");

                    b.Navigation("GeneratedRecaps");

                    b.Navigation("PlanParticipations");

                    b.Navigation("PlanVotes");

                    b.Navigation("Reactions");

                    b.Navigation("ReceivedNotifications");

                    b.Navigation("ReviewedFamilyJoinRequests");

                    b.Navigation("RevokedJoinCodes");

                    b.Navigation("TriggeredNotifications");

                    b.Navigation("UploadedMemories");
                });
#pragma warning restore 612, 618
        }
    }
}
